version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: django
    command: ./compose/local/start
    volumes:
      - .:/ai_blog
    ports:
      - '${PORT}:8000'
    environment:
      - DJANGO_READ_DOT_ENV_FILE=True
    env_file:
      - .env
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    container_name: pgdb
    env_file:
      - .env
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null
