# Generated by Django 5.0.6 on 2024-07-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(default=None, max_length=254, unique=True, verbose_name="email address"),
        ),
    ]
