# Generated by Django 5.0.6 on 2024-07-02 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default=None,
                max_length=250,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3, "the field must contain at least 3 characters")
                ],
                verbose_name="email address",
            ),
        ),
    ]
