# Generated by Django 5.0.6 on 2024-07-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_users", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="last name"),
        ),
    ]
