# Generated by Django 5.0.6 on 2024-07-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_users", "0005_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(null=True),
        ),
    ]
