#!/bin/bash

set -o errexit
set -o nounset

python src/manage.py makemigrations
python src/manage.py migrate
{
  python src/manage.py createsuperuser --noinput --email admin@gmail.com
  echo "User: admin@gmail.com | 1234 (see local.yml env var) Created"
} || {
  echo "User: admin@gmail.com | 1234 (see local.yml env var) Already exists"
}
python src/manage.py prepopulate --dont-repeat
python src/manage.py collectstatic --noinput
exec python src/manage.py runserver 0.0.0.0:8000
