# Generated by Django 5.0.6 on 2024-07-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_reply_parent_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_blocked",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="blocked",
        ),
    ]
