# Generated by Django 5.0.6 on 2024-07-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_post_is_blocked_remove_reply_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reply",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
