# Generated by Django 5.0.6 on 2024-07-08 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_comment_is_blocked_post_is_blocked_reply_is_blocked"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoReplyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delay_secs", models.PositiveIntegerField(default=0)),
                (
                    "comment",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="posts.comment"),
                ),
            ],
        ),
    ]
