# Generated by Django 5.0.6 on 2024-07-08 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_autoreplyconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autoreplyconfig",
            name="comment",
        ),
        migrations.AddField(
            model_name="autoreplyconfig",
            name="post",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.post",
            ),
            preserve_default=False,
        ),
    ]
